version: 3.1.{build}

image: Visual Studio 2019

install:
- ps: build/ci/appveyor/installDotnetCore3.1.ps1

before_build:
- cmd: dotnet restore

build_script:
- cmd: dotnet --info
- cmd: dotnet build
  
test_script:
- cmd: dotnet test .\tests\OpenGraphNet.Tests\OpenGraphNet.Tests.csproj
